"""Generate 00-governance/00-dossier-index.md and README.md for the Kilima Poker dossier from document front matter.
Run after adding or renaming documents:  python3 tools/make_index.py"""
import os, glob, sys
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "tools"))
from render import front_matter

SECTIONS = [("00-governance", "Governance"), ("01-product", "Product"), ("02-project", "Project management"),
            ("03-engineering", "Engineering"), ("04-quality", "Quality"), ("05-security", "Security"),
            ("06-operations", "Operations"), ("07-legal-compliance", "Legal and compliance (drafts)"),
            ("08-finance", "Finance and treasury"), ("09-handbook", "Engineering handbook")]

docs = []
for f in sorted(glob.glob(os.path.join(ROOT, "[0-9][0-9]-*", "*.md"))):
    if f.endswith("00-dossier-index.md"):
        continue
    meta, _ = front_matter(open(f, encoding="utf-8").read())
    docs.append((os.path.relpath(f, ROOT), meta))

LIFECYCLE = [
    ("Initiation (month 0–1, gate G0)", "KP-PRD-01, KP-LEG-01, KP-PRJ-01, KP-PRJ-02, KP-PRJ-04, KP-GOV-01"),
    ("Requirements and design (month 1–3)", "KP-PRD-02 to KP-PRD-05, KP-ENG-01 to KP-ENG-16, KP-SEC-01, KP-SEC-03"),
    ("Build (month 1–12)", "KP-ENG-11, KP-QA-01, KP-QA-02, KP-OPS-01, specs/openapi.yaml, specs/asyncapi.yaml, reference/test_vectors.json"),
    ("Alpha and Play Money Beta (month 6–8, gate G1)", "KP-QA-03, KP-QA-04, KP-OPS-02 to KP-OPS-04, KP-OPS-07, KP-OPS-06 (G1), KP-LEG-02, KP-LEG-03, KP-LEG-07"),
    ("Certification and licensing (month 8–12, gate G2)", "KP-ENG-13, KP-QA-05, KP-LEG-01, KP-LEG-04, KP-LEG-05, KP-LEG-06, KP-SEC-02"),
    ("Real Money launch (gate G3)", "KP-ENG-08, KP-FIN-01 to KP-FIN-04, KP-SEC-04, KP-OPS-05, KP-OPS-06 (G3)"),
    ("Network and expansion (gate G4)", "KP-ENG-14, KP-PRJ-03, KP-ENG-12 (new ADRs), Bridge integration (KP-ENG-01 §12)"),
]


def table(rows_for_md, link=True):
    out = ["| ID | Document | Owner | Version | Status |", "|---|---|---|---|---|"]
    for rel, m in rows_for_md:
        name = f"[{m['title']}]({rel})" if link else m["title"]
        out.append(f"| {m.get('id','')} | {name} | {m.get('owner','')} | {m.get('version','')} | {m.get('status','')} |")
    return out


idx = ["---", "id: KP-GOV-00", "title: Project Dossier Index", "subtitle: Every document the company keeps for Kilima Poker, from idea to Real Money",
       "version: 1.0", "owner: Programme Director", "status: Living document — generated by tools/make_index.py", "---", "",
       "# 1. About This Dossier", "",
       "This dossier holds all project documentation for Kilima Poker: product, project management, engineering, quality, security, operations, legal/compliance drafts, and finance. It is maintained as docs-as-code (KP-GOV-01): Markdown and specifications in Git are the source of truth; the PDFs in `dist/pdf/` are generated from them.", "",
       "Machine-readable artefacts:", "",
       "- `03-engineering/specs/openapi.yaml` — REST API contract (OpenAPI 3.1, generated and validated)",
       "- `03-engineering/specs/asyncapi.yaml` — real-time protocol (AsyncAPI 3.1, generated and validated)",
       "- `03-engineering/reference/poker_reference.py` + `test_vectors.json` — normative poker-engine reference and test vectors",
       "- `03-engineering/adr/` — architecture decision records",
       "- `templates/` and `.github/` — ADR, postmortem, release notes, change request, test charter, PR and issue templates, CODEOWNERS", ""]
n = 2
for folder, name in SECTIONS:
    rows = [(r, m) for r, m in docs if r.startswith(folder)]
    if not rows:
        continue
    idx += [f"# {n}. {name}", ""] + ["@widths 0.9,2.3,1.2,0.75,1.6"] + table(rows, link=False) + [""]
    n += 1
idx += [f"# {n}. Documents by Project Phase", "", "@widths 1.6,3.4", "| Phase | Documents used and produced |", "|---|---|"]
idx += [f"| {p} | {d} |" for p, d in LIFECYCLE] + [""]
open(os.path.join(ROOT, "00-governance", "00-dossier-index.md"), "w", encoding="utf-8").write("\n".join(idx))

readme = ["# Kilima Poker — Project Dossier", "",
          "Complete project documentation for **Kilima Poker**, a mobile-first online poker platform for African markets with a Play Money mode and licensed Real Money play, built as a B2C brand and a B2B operator network. Bridge (see the Bridge Casino dossier) will be added as a second game family after the poker launch.", "",
          "**Start here:** [Dossier index](00-governance/00-dossier-index.md) · [Architecture](03-engineering/01-system-architecture.md) · [Poker engine](03-engineering/06-poker-game-engine.md) · [Roadmap](01-product/03-mvp-scope-roadmap.md) · [Regulatory assessment](07-legal-compliance/01-regulatory-assessment.md)", "",
          "## Contents", ""]
for folder, name in SECTIONS:
    rows = [(r, m) for r, m in docs if r.startswith(folder)]
    readme += [f"### {name}", ""] + table(rows) + [""]
readme += ["### Specifications and references", "",
           "| Path | Content |", "|---|---|",
           "| [03-engineering/specs/openapi.yaml](03-engineering/specs/openapi.yaml) | REST API (OpenAPI 3.1) |",
           "| [03-engineering/specs/asyncapi.yaml](03-engineering/specs/asyncapi.yaml) | Real-time events (AsyncAPI 3.1) |",
           "| [03-engineering/reference/](03-engineering/reference/) | Poker-engine reference implementation and test vectors |",
           "| [03-engineering/adr/](03-engineering/adr/) | Architecture decision records |",
           "| [templates/](templates/) | ADR, postmortem, release notes, change request, test charter |", "",
           "## Building the PDFs", "",
           "```bash", "pip install reportlab pyyaml openapi-spec-validator",
           "python3 03-engineering/reference/poker_reference.py   # self-check evaluator, regenerate test vectors",
           "python3 tools/gen_specs.py                # regenerate openapi.yaml and asyncapi.yaml",
           "python3 tools/check_api_consistency.py    # documents ⇄ specs",
           "python3 tools/check_references.py         # every KP-/ADR reference exists",
           "python3 tools/make_index.py               # refresh the index and this README",
           "python3 tools/build.py                    # all PDFs → dist/pdf/  (or: build.py 03-engineering)", "```", "",
           "## Status", "",
           "Legal and compliance documents (`07-legal-compliance/`) and finance baselines (`08-finance/`) are **drafts for counsel and finance review** and must not be used externally before approval. Real Money is enabled only in licensed jurisdictions (KP-LEG-01).", ""]
open(os.path.join(ROOT, "README.md"), "w", encoding="utf-8").write("\n".join(readme))
print("index:", len(docs), "documents")
